### ISSUE TITLE
OSError: [Errno 61] No data available 

### ISSUE THREAD

**Issue by BenoitMorel** [amkozlov/eco-freq#7]
Hi Alexey,

I have installed eco-freq and run the test command:
`sudo ./ecofreq.py -c mock.cfg -l test.log`

I get the following stack:
```
~$ sudo ./ecofreq.py -c mock.cfg -l test.log
EcoFreq v0.0.1 (c) 2021 Alexey Kozlov

CPU model:                 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
CPU sockets/cores/threads: 1 / 2 / 4

RAPL CPU  domains: count = 1, hw_limit = 15.0 W, current_limit = 15.0 W
RAPL DRAM domains: count = 1, hw_limit = None W, current_limit = 0.0 W

DVFS settings:  driver = intel_pstate, governor = powersave
DVFS HW limits: 500 - 2700 MHz
DVFS policy:    500 - 2700 MHz


IPMI available: NO

Log file:     test.log
CO2 Provider: MockCO2Provider (interval = 10 sec)
CO2 Policy:   CPUPowerEcoPolicy(LinearGovernor)
Monitors:     PowercapEnergyMonitor (interval = 5 sec), CPUFreqMonitor (interval = 5 sec)

#Timestamp           	  gCO2/kWh	Fmax [Mhz]	Favg [Mhz]	CPU_Pmax [W]	GPU_Pmax [W]	SYS_Pavg [W]	Energy [J]	   CO2 [g]
2021-06-15T10:30:23 	       254	      2700	       911	      15.000	          NA	       9.193	    91.930	     0.006
Exception:  (<class 'OSError'>, OSError(61, 'No data available'), <traceback object at 0x7f038c051948>)
OSError: [Errno 61] No data available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ecofreq.py", line 1250, in spin
    self.update_co2()
  File "./ecofreq.py", line 1222, in update_co2
    self.co2policy.set_co2(co2)
  File "./ecofreq.py", line 1121, in set_co2
    p.set_co2(co2)
  File "./ecofreq.py", line 1047, in set_co2
    self.set_power(self.power)
  File "./ecofreq.py", line 1042, in set_power
    LinuxPowercapHelper.set_power_limit(power_uw)
  File "./ecofreq.py", line 402, in set_power_limit
    cls.set_package_power_limit(pkg, power, unit)
  File "./ecofreq.py", line 392, in set_package_power_limit
    write_value(cls.package_file(pkg, "constraint_0_power_limit_uw"), val)
  File "./ecofreq.py", line 34, in write_value
    f.write(str(val))
OSError: [Errno 61] No data available

During handling of the above exception, another exception occurred:

OSError: [Errno 61] No data available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ecofreq.py", line 1328, in <module>
    ef.spin()
  File "./ecofreq.py", line 1257, in spin
    self.co2policy.reset()
  File "./ecofreq.py", line 1125, in reset
    p.reset()
  File "./ecofreq.py", line 1050, in reset
    self.set_power(self.pmax)
  File "./ecofreq.py", line 1042, in set_power
    LinuxPowercapHelper.set_power_limit(power_uw)
  File "./ecofreq.py", line 402, in set_power_limit
    cls.set_package_power_limit(pkg, power, unit)
  File "./ecofreq.py", line 392, in set_package_power_limit
    write_value(cls.package_file(pkg, "constraint_0_power_limit_uw"), val)
  File "./ecofreq.py", line 34, in write_value
    f.write(str(val))
OSError: [Errno 61] No data available
```

Any clue what's causing this?
Cheers,
Benoit

**Comment by amkozlov** [comment]
Interesting, seems like RAPL is disabled on your system. Could you please try following the suggestions here:
https://askubuntu.com/questions/1231091/tee-constraint-0-power-limit-uw-no-data-available

thanks!

**Comment by BenoitMorel** [comment]
It doesn't look good. Here are the outputs of the suggested commands. 
```
~$ cat /sys/class/powercap/intel-rapl/intel-rapl\:0/enabled 
0
```

```
~$ echo 1 | sudo tee /sys/class/powercap/intel-rapl/intel-rapl\:0/enabled 
1
tee: '/sys/class/powercap/intel-rapl/intel-rapl:0/enabled': Function not implemented
```


```
~$ echo "94500000" | sudo tee /sys/class/powercap/intel-rapl/intel-rapl\:0/constraint_0_power_limit_uw 
94500000
tee: '/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw': No data available
```

```
~$dmesg | grep locked
[13576.460261] powercap intel-rapl:0: package locked by BIOS, monitoring only
```

**Comment by amkozlov** [comment]
OK, so apparently RAPL is either disabled in BIOS or not available on this laptop. Good to know this situation exists, I will add a check and print a proper error message.

**Comment by amkozlov** [comment]
Now it should detect that RAPL is disabled and use frequency scaling instead, could you please double-check?

**Comment by BenoitMorel** [comment]
It works, thank you!
